server:
  port: 8085
  
spring:
  application:
    name: USERCONFIGSERVER  
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rutujakadu23/Hotel-Ratings-Service-Application
          clone-on-start: true