
spring:
  application:
    name: USERRATINGSERVICE

  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices
  
  config:
    import: "configserver:http://localhost:8085"    
       
   
   
server:
  port: 8083

#  
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
